version: '3.9'

services:
  db:
      container_name: pg_db
      image: postgres:14-alpine
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: my_db
      volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      ports:
      - "5432:5432"
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
   nats:
      image: nats:latest
      command: --js --debug --trace --sd /data -p 4222 -m 8222
      ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      volumes:
      - ./jetstream-cluster/n1:/data

  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "-connz -varz -channelz -serverz -subz -healthz -routez http://host.docker.internal:8222"
    ports:
      - "7777:7777"
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"